CLASS LHC_TRANSFERPRICE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR TransferPrice
        RESULT result,
      withPopup FOR MODIFY
            IMPORTING keys FOR ACTION TransferPrice~withPopup RESULT result.
ENDCLASS.

CLASS LHC_TRANSFERPRICE IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD withPopup.
  IF 0 = 0.
  ENDIF.
  ENDMETHOD.

ENDCLASS.
