*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: /EXAOTP/T_MODE..................................*
DATA:  BEGIN OF STATUS_/EXAOTP/T_MODE                .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/EXAOTP/T_MODE                .
CONTROLS: TCTRL_/EXAOTP/T_MODE
            TYPE TABLEVIEW USING SCREEN '0009'.
*...processing: /EXAOTP/T_TP_DEF................................*
DATA:  BEGIN OF STATUS_/EXAOTP/T_TP_DEF              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/EXAOTP/T_TP_DEF              .
*...processing: /EXAOTP/V_DEFCOL................................*
TABLES: /EXAOTP/V_DEFCOL, */EXAOTP/V_DEFCOL. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_DEFCOL
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_/EXAOTP/V_DEFCOL. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_DEFCOL.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_DEFCOL_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_DEFCOL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_DEFCOL_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_DEFCOL_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_DEFCOL.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_DEFCOL_TOTAL.

*...processing: /EXAOTP/V_LE_CUR................................*
TABLES: /EXAOTP/V_LE_CUR, */EXAOTP/V_LE_CUR. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_LE_CUR
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_/EXAOTP/V_LE_CUR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_LE_CUR.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_LE_CUR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_LE_CUR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_LE_CUR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_LE_CUR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_LE_CUR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_LE_CUR_TOTAL.

*...processing: /EXAOTP/V_M_DEP.................................*
TABLES: /EXAOTP/V_M_DEP, */EXAOTP/V_M_DEP. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_M_DEP
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_/EXAOTP/V_M_DEP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_M_DEP.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_M_DEP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_DEP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_DEP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_M_DEP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_DEP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_DEP_TOTAL.

*...processing: /EXAOTP/V_M_PRM.................................*
TABLES: /EXAOTP/V_M_PRM, */EXAOTP/V_M_PRM. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_M_PRM
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_/EXAOTP/V_M_PRM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_M_PRM.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_M_PRM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_PRM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_PRM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_M_PRM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_PRM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_PRM_TOTAL.

*...processing: /EXAOTP/V_M_SPRM................................*
TABLES: /EXAOTP/V_M_SPRM, */EXAOTP/V_M_SPRM. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_M_SPRM
TYPE TABLEVIEW USING SCREEN '0013'.
DATA: BEGIN OF STATUS_/EXAOTP/V_M_SPRM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_M_SPRM.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_M_SPRM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_SPRM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_SPRM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_M_SPRM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_M_SPRM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_M_SPRM_TOTAL.

*...processing: /EXAOTP/V_TP_ALG................................*
TABLES: /EXAOTP/V_TP_ALG, */EXAOTP/V_TP_ALG. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_TP_ALG
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_/EXAOTP/V_TP_ALG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_TP_ALG.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_TP_ALG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_ALG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_ALG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_TP_ALG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_ALG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_ALG_TOTAL.

*...processing: /EXAOTP/V_TP_ATT................................*
TABLES: /EXAOTP/V_TP_ATT, */EXAOTP/V_TP_ATT. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_TP_ATT
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_/EXAOTP/V_TP_ATT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_TP_ATT.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_TP_ATT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_ATT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_ATT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_TP_ATT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_ATT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_ATT_TOTAL.

*...processing: /EXAOTP/V_TP_BUD................................*
TABLES: /EXAOTP/V_TP_BUD, */EXAOTP/V_TP_BUD. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_TP_BUD
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_/EXAOTP/V_TP_BUD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_TP_BUD.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_TP_BUD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_BUD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_BUD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_TP_BUD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_BUD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_BUD_TOTAL.

*...processing: /EXAOTP/V_TP_FLD................................*
TABLES: /EXAOTP/V_TP_FLD, */EXAOTP/V_TP_FLD. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_TP_FLD
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_/EXAOTP/V_TP_FLD. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_TP_FLD.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_TP_FLD_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_FLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_FLD_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_TP_FLD_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_FLD.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_FLD_TOTAL.

*...processing: /EXAOTP/V_TP_PM.................................*
TABLES: /EXAOTP/V_TP_PM, */EXAOTP/V_TP_PM. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_TP_PM
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_/EXAOTP/V_TP_PM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_TP_PM.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_TP_PM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_PM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_PM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_TP_PM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_TP_PM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_TP_PM_TOTAL.

*...processing: /EXAOTP/V_VAL_LE................................*
TABLES: /EXAOTP/V_VAL_LE, */EXAOTP/V_VAL_LE. "view work areas
CONTROLS: TCTRL_/EXAOTP/V_VAL_LE
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_/EXAOTP/V_VAL_LE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/EXAOTP/V_VAL_LE.
* Table for entries selected to show on screen
DATA: BEGIN OF /EXAOTP/V_VAL_LE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_VAL_LE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_VAL_LE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /EXAOTP/V_VAL_LE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /EXAOTP/V_VAL_LE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /EXAOTP/V_VAL_LE_TOTAL.

*.........table declarations:.................................*
TABLES: */EXAOTP/T_MODE                .
TABLES: */EXAOTP/T_TP_DEF              .
TABLES: /EXAOTP/T_CCREP                .
TABLES: /EXAOTP/T_CCREPT               .
TABLES: /EXAOTP/T_DEFCOL               .
TABLES: /EXAOTP/T_DFCL_T               .
TABLES: /EXAOTP/T_LE_CUR               .
TABLES: /EXAOTP/T_MODE                 .
TABLES: /EXAOTP/T_M_DEP                .
TABLES: /EXAOTP/T_M_PRM                .
TABLES: /EXAOTP/T_M_PRMT               .
TABLES: /EXAOTP/T_M_SPRM               .
TABLES: /EXAOTP/T_TP_ALG               .
TABLES: /EXAOTP/T_TP_ALT               .
TABLES: /EXAOTP/T_TP_ART               .
TABLES: /EXAOTP/T_TP_ATT               .
TABLES: /EXAOTP/T_TP_BGT               .
TABLES: /EXAOTP/T_TP_BUD               .
TABLES: /EXAOTP/T_TP_DEF               .
TABLES: /EXAOTP/T_TP_FLD               .
TABLES: /EXAOTP/T_TP_FLT               .
TABLES: /EXAOTP/T_TP_PM                .
TABLES: /EXAOTP/T_TP_PMT               .
TABLES: /EXAOTP/T_VAL_LE               .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
